# Generated by Django 5.1.4 on 2025-01-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('nick', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('salt', models.TextField()),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
                ('iv', models.TextField()),
                ('salt_llave', models.TextField()),
            ],
        ),
    ]
